### ISSUE TITLE
mangrove wood

### ISSUE THREAD

**Issue by meadowsys** [Love-and-Tolerance/Love-and-Tolerance#164]
- [x] mangrove log end
- [x] mangrove log side
- [x] stripped mangrove log end
- [x] stripped mangrove log side
- [x] mangrove roots top
- [x] mangrove roots side
- [x] muddy mangrove roots top
- [x] muddy mangrove roots side
- [x] mangrove planks
- [x] mangrove leaves
- [x] mangrove boat
- [x] mangrove boat item
- [x] mangrove chest boat
- [x] mangrove chest boat item
- [x] mangrove door
- [x] mangrove door item
- [x] mangrove trapdoor
- [x] mangrove sign
- [x] mangrove sign item
- [x] mangrove hanging sign entity
- [x] mangrove hanging sign item
- [x] mangrove hanging sign gui
- [x] mangrove propagule
- [x] mangrove propagule hanging
- [x] mangrove propagule item

**Comment by SilkRose** [comment]
Moved mud blocks to #196
