### ISSUE TITLE
Cod textures are inconsistent

### ISSUE THREAD

**Issue by ashy1227** [Love-and-Tolerance/Love-and-Tolerance#185]
#### What should be happening?

Textures should be consistent

#### What is actually happening?

The item is blue and red, the entity is brown, and the bucket looks like vanilla cod

**Comment by meadowsys** [comment]
<img width="522" alt="later™" src="https://user-images.githubusercontent.com/49562048/178169395-5005c205-129b-48c5-92c0-59c29297d0e3.png">
