### ISSUE TITLE
Custom block models that need to be done (pre1.16)

### ISSUE THREAD

**Issue by Sollace** [Love-and-Tolerance/Love-and-Tolerance#20]
- [x] oak trapdoor
- [x] iron trapdoor (done) - @VelvetRemedy 
- [ ] activater rail
- [ ] rail
- [ ] detector rail
- [ ] powered rail
- [ ] spruce door
- [ ] acacia door
- [ ] dark oak door
- [ ] birch door
- [ ] jungle door

**Comment by VelvetRemedy** [comment]
Merged this into the other block models issue, no reason to have them seperated.
