### ISSUE TITLE
Custom block models that need to be done

### ISSUE THREAD

**Issue by Sollace** [Love-and-Tolerance/Love-and-Tolerance#21]
- [ ] mangrove door
- [ ] crimson door
- [ ] warped door
- [ ] mangrove trapdoor
- [ ] crimson trap door
- [ ] warped trap door
- [x] oak trapdoor
- [x] iron trapdoor
- [ ] activater rail
- [ ] rail
- [ ] detector rail
- [ ] powered rail
- [ ] spruce door
- [ ] acacia door
- [ ] dark oak door
- [ ] birch door
- [ ] jungle door

**Comment by killjoy1221** [comment]
Why would optifine be involved? Block models are vanilla.

**Comment by Sollace** [comment]
Derp. For some reason I forgot custom models was vanilla.

**Comment by SilkRose** [comment]
Moved to the add-on repo in [#1](https://github.com/Love-and-Tolerance/3d-Models-Addon/issues/1), [#2](https://github.com/Love-and-Tolerance/3d-Models-Addon/issues/2), [#3](https://github.com/Love-and-Tolerance/3d-Models-Addon/issues/3).
