### ISSUE TITLE
Cocoa beans texture is shifted

### ISSUE THREAD

**Issue by whitebear60** [Love-and-Tolerance/Love-and-Tolerance#223]
#### What should be happening?

The cocoa beans texture should be normally positioned

#### What is actually happening?

The texture is shifted (at least for full-grown state) and shows transparent pixels

#### Additional comments?

See the screenshot below
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42472132/212910608-150c5b9e-2647-497d-a52f-fb836bfc2c13.png">

**Comment by SilkRose** [comment]
I'll look into it. What version are you playing on, @whitebear60 ?

**Comment by whitebear60** [comment]
1.19.3, L-T version 12, I believe...

**Comment by SilkRose** [comment]
Okay, thank you.

**Comment by whitebear60** [comment]
L-T_1.3.0-format.12-dbsw-ct-vsp-pbd-ob-fb-mlp.zip, to be more precise with the pack version and bundling
