### ISSUE TITLE
z-fighting issues with redstone dust

### ISSUE THREAD

**Issue by whitebear60** [Love-and-Tolerance/Love-and-Tolerance#226]
#### What should be happening?

The redstone dust texture (particularly the default X-shaped state) should look normal without any artifacts

#### What is actually happening?

The redstone dust texture suffers from z-fighting issues (see screenshot below)

#### Additional comments?

Love & Tolerance bundle used: L-T_1.3.0-format.12-dbsw-ct-vsp-pbd-ob-fb-mlp
Minecraft 1.19.3 with Quilt 0.18.1-beta.41
macOS Ventura 13.0.1, if that will change something

![image](https://user-images.githubusercontent.com/42472132/213903962-3a6b976c-5917-4342-938d-c446ec5f339f.png)

**Comment by SilkRose** [comment]
I'll look into this after I get woke up, thank you for posting!

**Comment by whitebear60** [comment]
I haven't tested all states, but the angled texture seems to be having this issues too (if the fix for one won't fix the other, I don't know how the textures are made in Minecraft...)
![image](https://user-images.githubusercontent.com/42472132/213914057-2e3590f4-1e8b-4644-a3f6-69dfbfec8c61.png)

**Comment by SilkRose** [comment]
The fix fixes it for all states.
