### ISSUE TITLE
Entity textures that need to be done.

### ISSUE THREAD

**Issue by Sollace** [Love-and-Tolerance/Love-and-Tolerance#27]
Camel:
- [x] camel

Cats:
- [x] all black
- [x] collar
- [x] british shorthair
- [x] calico
- [x] jellie
- [x] persian
- [x] ragdoll
- [x] tabby
- [x] white

Cows
- [x] Brown mooshroom

Fish
- [ ] tropical
- [ ] tropical patterns

Foxes
- [x] fox/sleeping
- [x] snow fox/sleeping

Pandas
- [x] aggressive
- [x] brown
- [x] lazy
- [x] panda
- [x] playful
- [x] weak
- [x] worried

Illagers
- [ ] evoker
- [x] evoker fangs
- [ ] illusioner
- [ ] vindicator
- [ ] pillager
- [ ] ravager
- [x] vex
- [x] vex charging

Llamas
- [x] trader llama decor

Piglins
- [x] piglin
- [ ] piglin brute
- [ ] hoglin
- [ ] zoglin

Iron golem
- [x] low dmg
- [x] med dmg
- [x] high dmg

Other
- [x] phantoms
- [x] conduit
- [X] dolphin

**Comment by meadowsys** [comment]
unfinished items superceded by #266, #267, #268, #269, #270, #271, #272, #273, #274 .. ~vt
