### ISSUE TITLE
Outline colour on maps and elytra are too bright

### ISSUE THREAD

**Issue by Sollace** [Love-and-Tolerance/Love-and-Tolerance#29]
<img src="https://cdn.discordapp.com/attachments/621069869797867545/699178071437213732/unknown.png"></img>

**Comment by VelvetRemedy** [comment]
I don't think they are, I think there fine.

**Comment by Sollace** [comment]
Imo the outlines should be darker than the fills. Either the outlines should be darker than this, or the fills should be brighter.

Currently it looks like they're glowing.
