### ISSUE TITLE
completely redo/fix lang/eq_eq.json

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [Love-and-Tolerance/Love-and-Tolerance#90]
![ProblemPic](https://user-images.githubusercontent.com/60839302/83093788-b779a380-a0d2-11ea-84f6-17ecbc1105ab.png)  
I was wondering if there are duplicate keys, for I saw two "advancements.story.enchant_item.title".

**Comment by PCelestia** [comment]
there definitely shouldnt be two

**Comment by Andy-K-Sparklight** [comment]
But actually there are...
![批注 2020-05-28 114959](https://user-images.githubusercontent.com/60839302/83096937-7c2ea300-a0d9-11ea-9ecf-bf9753f2984d.png)

**Comment by PCelestia** [comment]
yea, will fix

**Comment by PCelestia** [comment]
@Andy-K-Sparklight join our discord? https://love-tolerance.com/discord

**Comment by Andy-K-Sparklight** [comment]
Discord has rejected my request for I'm using a proxy... And I don't think I can still visit github if I close it (So Sad).

**Comment by PCelestia** [comment]
oh ok, np
